/**
 * Application Error Codes
 * Centralized error codes for consistent error handling across the application
 */

export const ERROR_CODES = {
  // General errors
  SERVER_ERROR: 'SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',

  // Authentication & Authorization errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_SLUG: 'INVALID_SLUG',
  SLUG_TAKEN: 'SLUG_TAKEN',

  // Resource errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',

  // File upload errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Portfolio specific
  PORTFOLIO_NOT_FOUND: 'PORTFOLIO_NOT_FOUND',
  PORTFOLIO_NOT_PUBLISHED: 'PORTFOLIO_NOT_PUBLISHED',
  PORTFOLIO_ALREADY_PUBLISHED: 'PORTFOLIO_ALREADY_PUBLISHED',

  // Template specific
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_VALIDATION_ERROR: 'TEMPLATE_VALIDATION_ERROR',
  INVALID_TEMPLATE_CONTENT: 'INVALID_TEMPLATE_CONTENT',

  // Case study specific
  CASE_STUDY_NOT_FOUND: 'CASE_STUDY_NOT_FOUND',

  // Subdomain specific
  SUBDOMAIN_TAKEN: 'SUBDOMAIN_TAKEN',
  SUBDOMAIN_INVALID: 'SUBDOMAIN_INVALID',

  // Deployment specific
  DEPLOYMENT_FAILED: 'DEPLOYMENT_FAILED',
  VERCEL_API_ERROR: 'VERCEL_API_ERROR',

  // PDF generation
  PDF_GENERATION_FAILED: 'PDF_GENERATION_FAILED',

  // Permission errors
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  OWNERSHIP_REQUIRED: 'OWNERSHIP_REQUIRED',
  PREMIUM_REQUIRED: 'PREMIUM_REQUIRED'
};

export default ERROR_CODES;
